version: "3"

services:
  backend:
    build: ./backend
    expose:
      - "3000"
    ports:
      - "80:3000"
    volumes:
      - "./backend:/usr/src/app"
      - "/usr/src/app/node_modules"

  fronend:
    build: ./frontend
    expose:
        - "3000"
    ports:
        - "8080:3000"
    volumes:
        - "./frontend:/usr/src/app"
        - "/usr/src/app/node_modules"
